export const article = {
  title: "The Window",
  paragraphs: [
    "There are afternoons when lying still feels less like idleness than a form of study. Thought loosens from the day and slips among remembered rooms. The breeze comes through the window, the curtain hesitates at the sill, and light arrives in fragments, as if the world outside were moving backward while the chamber stays perfectly still.",
    "I once read a sentence that stopped me cold: we do not recover the past, we rewrite it in the language our present selves can bear. Since then I have distrusted the neatness of memory. What returns to us is not a preserved relic but a revised account, polished by desire, shame, convenience, and whatever story we need in order to continue.",
    "It is tempting to believe we choose freely and only afterward call the result fate. Yet so often the road laid before us has been softened, lit, and named in advance. Power rarely drags us by force when it can persuade us to walk willingly. We mistake arrangement for freedom because the invitation is beautiful and the pressure is quiet.",
    "Society changes its measure lines as a growing child marks height against a wall. What was once shared experience hardens into abstract categories, and those categories return to govern the people who made them. I have become suspicious of how quickly I sort before I understand. Labels arrive first, explanation later, and by then the judgment has already taken root.",
    "We speak of modern life as if its tragedy were forgetting, but I think the deeper terror is that forgetting has become difficult. Messages, locations, searches, purchases, and private hesitations are kept as though a court might someday ask for proof. The past is no longer a fading countryside. It is an archive that follows us, tidy and searchable.",
    "Worse still, we build that archive ourselves. We authorize it, confirm it, restore it from backup, and call the process convenience. Each bright little button asks for consent with such politeness that refusal begins to feel rude. We carve our own memorial tablets and set them upright in a graveyard named the future.",
    "For all that machinery, the motive may still be embarrassingly old: we fear being left alone with no witness. To be seen, even by systems that do not love us, can feel preferable to vanishing. Exposure borrows the costume of intimacy. The ledger grows because silence frightens us more than surveillance.",
    "A fly struck the glass beside my bed and snapped the thread of thought. It threw itself again and again against a barrier it could not comprehend, frantic before a world it could see and could not enter. I rose to open the window and wondered, with less certainty than I would like, how often I have done the same against clearer walls.",
    "The room changed at once when the pane swung outward. Not because the world had altered, but because one small obstruction had been named and moved. Perhaps that is all lucidity ever is: not escape, not mastery, only the brief mercy of discovering which surface has been stopping the breath."
  ]
};
